#include <GL/glew.h>
#include <SDL2/SDL.h>
#include "ext/linmath.h"
#include "procgl_base.h"
#include "wave.h"
#include "texture.h"
#include "viewer.h"
#include "shader.h"
#include "postproc.h"
#include "vertex.h"
#include "model.h"
#include "shape.h"
#include "gbuffer.h"
#include "../game/game_state.h"
